-- Official DU college baseline sourced from:
-- https://www.du.ac.in/index.php?page=colleges-at-du
-- The source contains 92 links in the college/other-institution sections,
-- including one duplicate, producing 91 unique institution names.
-- Only names and stable slugs are loaded. Unsupported fields remain empty/null.

insert into public.colleges (
  name,
  slug,
  short_description,
  campus,
  location,
  categories,
  popular_courses,
  college_type,
  hero_image_url
)
values
  ('Acharya Narendra Dev College', 'acharya-narendra-dev-college', null, '', '', '{}', '{}', '', null),
  ('Aditi Mahavidyalaya', 'aditi-mahavidyalaya', null, '', '', '{}', '{}', '', null),
  ('Aryabhatta College', 'aryabhatta-college', null, '', '', '{}', '{}', '', null),
  ('Atma Ram Sanatan Dharma College', 'atma-ram-sanatan-dharma-college', null, '', '', '{}', '{}', '', null),
  ('Bhagini Nivedita College', 'bhagini-nivedita-college', null, '', '', '{}', '{}', '', null),
  ('Bharati College', 'bharati-college', null, '', '', '{}', '{}', '', null),
  ('Bhaskaracharya College of Applied Sciences', 'bhaskaracharya-college-of-applied-sciences', null, '', '', '{}', '{}', '', null),
  ('Bhim Rao Ambedkar College', 'bhim-rao-ambedkar-college', null, '', '', '{}', '{}', '', null),
  ('College of Art', 'college-of-art', null, '', '', '{}', '{}', '', null),
  ('College of Vocational Studies', 'college-of-vocational-studies', null, '', '', '{}', '{}', '', null),
  ('Daulat Ram College', 'daulat-ram-college', null, '', '', '{}', '{}', '', null),
  ('Delhi College of Arts & Commerce', 'delhi-college-of-arts-and-commerce', null, '', '', '{}', '{}', '', null),
  ('Deshbandhu College(Morning)', 'deshbandhu-college-morning', null, '', '', '{}', '{}', '', null),
  ('Deen Dayal Upadhyaya College', 'deen-dayal-upadhyaya-college', null, '', '', '{}', '{}', '', null),
  ('Durga Bai Deshmukh College of Special Edu.(VI)', 'durga-bai-deshmukh-college-of-special-edu-vi', null, '', '', '{}', '{}', '', null),
  ('Dyal Singh College', 'dyal-singh-college', null, '', '', '{}', '{}', '', null),
  ('Dyal Singh College (Evening)', 'dyal-singh-college-evening', null, '', '', '{}', '{}', '', null),
  ('Gargi College', 'gargi-college', null, '', '', '{}', '{}', '', null),
  ('Hans Raj College', 'hans-raj-college', null, '', '', '{}', '{}', '', null),
  ('Hindu College', 'hindu-college', null, '', '', '{}', '{}', '', null),
  ('Indira Gandhi Institute of Physical Education & Sports Sciences', 'indira-gandhi-institute-of-physical-education-and-sports-sciences', null, '', '', '{}', '{}', '', null),
  ('Indraprastha College for Women', 'indraprastha-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Institute of Home Economics', 'institute-of-home-economics', null, '', '', '{}', '{}', '', null),
  ('Janki Devi Memorial College', 'janki-devi-memorial-college', null, '', '', '{}', '{}', '', null),
  ('Jesus & Mary College', 'jesus-and-mary-college', null, '', '', '{}', '{}', '', null),
  ('Kalindi College for Women', 'kalindi-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Kamla Nehru College for Women', 'kamla-nehru-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Keshav Mahavidyalaya', 'keshav-mahavidyalaya', null, '', '', '{}', '{}', '', null),
  ('Kirori Mal College', 'kirori-mal-college', null, '', '', '{}', '{}', '', null),
  ('Lady Irwin College', 'lady-irwin-college', null, '', '', '{}', '{}', '', null),
  ('Lady Shri Ram College for Women', 'lady-shri-ram-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Lakshmi Bai College for Women', 'lakshmi-bai-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Maharaja Agarsen College', 'maharaja-agarsen-college', null, '', '', '{}', '{}', '', null),
  ('Maharshi Valmiki College of Education', 'maharshi-valmiki-college-of-education', null, '', '', '{}', '{}', '', null),
  ('Maitreyi College for Women', 'maitreyi-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Mata Sundri College for Women', 'mata-sundri-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Miranda House', 'miranda-house', null, '', '', '{}', '{}', '', null),
  ('Moti Lal Nehru College', 'moti-lal-nehru-college', null, '', '', '{}', '{}', '', null),
  ('Moti Lal Nehru College (Evening)', 'moti-lal-nehru-college-evening', null, '', '', '{}', '{}', '', null),
  ('P.G.D.A.V. College', 'p-g-d-a-v-college', null, '', '', '{}', '{}', '', null),
  ('P.G.D.A.V. College (Evening)', 'p-g-d-a-v-college-evening', null, '', '', '{}', '{}', '', null),
  ('Rajdhani College', 'rajdhani-college', null, '', '', '{}', '{}', '', null),
  ('Rajkumari Amrit Kaur College of Nursing', 'rajkumari-amrit-kaur-college-of-nursing', null, '', '', '{}', '{}', '', null),
  ('Ram Lal Anand College', 'ram-lal-anand-college', null, '', '', '{}', '{}', '', null),
  ('Ramanujan College', 'ramanujan-college', null, '', '', '{}', '{}', '', null),
  ('Ramjas College', 'ramjas-college', null, '', '', '{}', '{}', '', null),
  ('Satyawati College', 'satyawati-college', null, '', '', '{}', '{}', '', null),
  ('Satyawati College (Evening)', 'satyawati-college-evening', null, '', '', '{}', '{}', '', null),
  ('School of Open Learning ( Erstwhile School of Correspondence & Continuing Education)', 'school-of-open-learning-erstwhile-school-of-correspondence-continuing-education', null, '', '', '{}', '{}', '', null),
  ('Shaheed Bhagat Singh College', 'shaheed-bhagat-singh-college', null, '', '', '{}', '{}', '', null),
  ('Shaheed Bhagat Singh College (Evening)', 'shaheed-bhagat-singh-college-evening', null, '', '', '{}', '{}', '', null),
  ('Shaheed Rajguru College of Applied Sciences for Women', 'shaheed-rajguru-college-of-applied-sciences-for-women', null, '', '', '{}', '{}', '', null),
  ('Shaheed Sukhdev College of Business Studies', 'shaheed-sukhdev-college-of-business-studies', null, '', '', '{}', '{}', '', null),
  ('Shivaji College', 'shivaji-college', null, '', '', '{}', '{}', '', null),
  ('Shri Ram College of Commerce', 'shri-ram-college-of-commerce', null, '', '', '{}', '{}', '', null),
  ('Shyam Lal College', 'shyam-lal-college', null, '', '', '{}', '{}', '', null),
  ('Shyam Lal College (Evening)', 'shyam-lal-college-evening', null, '', '', '{}', '{}', '', null),
  ('Shyama Prasad Mukherji College for Women', 'shyama-prasad-mukherji-college-for-women', null, '', '', '{}', '{}', '', null),
  ('Sri Aurobindo College', 'sri-aurobindo-college', null, '', '', '{}', '{}', '', null),
  ('Sri Aurobindo College (Evening)', 'sri-aurobindo-college-evening', null, '', '', '{}', '{}', '', null),
  ('Sri Guru Gobind Singh College of Commerce', 'sri-guru-gobind-singh-college-of-commerce', null, '', '', '{}', '{}', '', null),
  ('Sri Guru Nanak Dev Khalsa College', 'sri-guru-nanak-dev-khalsa-college', null, '', '', '{}', '{}', '', null),
  ('Sri Guru Tegh Bahadur Khalsa College', 'sri-guru-tegh-bahadur-khalsa-college', null, '', '', '{}', '{}', '', null),
  ('Sri Venkateswara College', 'sri-venkateswara-college', null, '', '', '{}', '{}', '', null),
  ('St. Stephen''s College', 'st-stephens-college', null, '', '', '{}', '{}', '', null),
  ('Swami Shraddhanand College', 'swami-shraddhanand-college', null, '', '', '{}', '{}', '', null),
  ('Vivekananda College', 'vivekananda-college', null, '', '', '{}', '{}', '', null),
  ('Zakir Husain Delhi College', 'zakir-husain-delhi-college', null, '', '', '{}', '{}', '', null),
  ('Zakir Husain Post Graduate Evening College', 'zakir-husain-post-graduate-evening-college', null, '', '', '{}', '{}', '', null),
  ('Ahilya Bai College of Nursing', 'ahilya-bai-college-of-nursing', null, '', '', '{}', '{}', '', null),
  ('Amar Jyoti Institute of Physiotherapy', 'amar-jyoti-institute-of-physiotherapy', null, '', '', '{}', '{}', '', null),
  ('Ayurvedic & Unani Tibia College', 'ayurvedic-and-unani-tibia-college', null, '', '', '{}', '{}', '', null),
  ('Chacha Nehru Bal Chikitsalaya', 'chacha-nehru-bal-chikitsalaya', null, '', '', '{}', '{}', '', null),
  ('College of Nursing at Army Hospital (R&R)', 'college-of-nursing-at-army-hospital-r-r', null, '', '', '{}', '{}', '', null),
  ('Delhi Institute of Pharmaceutical Sciences and Research', 'delhi-institute-of-pharmaceutical-sciences-and-research', null, '', '', '{}', '{}', '', null),
  ('Florence Nightingale College of Nursing', 'florence-nightingale-college-of-nursing', null, '', '', '{}', '{}', '', null),
  ('Holy Family College of Nursing', 'holy-family-college-of-nursing', null, '', '', '{}', '{}', '', null),
  ('Lady Hardinge Medical College', 'lady-hardinge-medical-college', null, '', '', '{}', '{}', '', null),
  ('Maulana Azad Institute of Dental Sciences', 'maulana-azad-institute-of-dental-sciences', null, '', '', '{}', '{}', '', null),
  ('Maulana Azad Medical College', 'maulana-azad-medical-college', null, '', '', '{}', '{}', '', null),
  ('Nehru Homeopathic Medical College & Hospital', 'nehru-homeopathic-medical-college-and-hospital', null, '', '', '{}', '{}', '', null),
  ('Netaji Subhash Institute of Technology', 'netaji-subhash-institute-of-technology', null, '', '', '{}', '{}', '', null),
  ('National Institute of Health & Family Welfare', 'national-institute-of-health-and-family-welfare', null, '', '', '{}', '{}', '', null),
  ('Pt. Deendayal Upadhyaya Institute of Physically Handicapped', 'pt-deendayal-upadhyaya-institute-of-physically-handicapped', null, '', '', '{}', '{}', '', null),
  ('Kasturba Hospital', 'kasturba-hospital', null, '', '', '{}', '{}', '', null),
  ('Institute of Human Behaviour & Allied Sciences', 'institute-of-human-behaviour-and-allied-sciences', null, '', '', '{}', '{}', '', null),
  ('G.B. Pant Hospital', 'g-b-pant-hospital', null, '', '', '{}', '{}', '', null),
  ('All India Institute of Ayurveda', 'all-india-institute-of-ayurveda', null, '', '', '{}', '{}', '', null),
  ('School of Rehabilitation Sciences', 'school-of-rehabilitation-sciences', null, '', '', '{}', '{}', '', null),
  ('University College of Medical Sciences', 'university-college-of-medical-sciences', null, '', '', '{}', '{}', '', null),
  ('Vallabhbhai Patel Chest Institute', 'vallabhbhai-patel-chest-institute', null, '', '', '{}', '{}', '', null)
on conflict (slug) do nothing;